name: Code Quality Checks

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-client:
    name: Lint Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/client
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run format

  lint-server:
    name: Lint Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/server
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm run format
